version: 2

before:
  hooks:
    - go mod tidy

gomod:
  proxy: true

builds:
  - main: ./cmd/mulval
    binary: mulval
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -cover
    ldflags:
      - -s -w
      - -X github.com/ctfer-io/mulval/cmd/mulval.Version={{.Version}}
      - -X github.com/ctfer-io/mulval/cmd/mulval.Commit={{.Commit}}
      - -X github.com/ctfer-io/mulval/cmd/mulval.Date={{.Date}}
      - -X github.com/ctfer-io/mulval/cmd/mulval.BuiltBy=goreleaser

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

source:
  enabled: true

checksum: {}

sboms:
  - artifacts: source
