// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/api/v1/analysis/analysis.proto

package analysis

import (
	longrunningpb "cloud.google.com/go/longrunning/autogen/longrunningpb"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lifecycle states of an analysis.
type Analysis_State int32

const (
	Analysis_STATE_UNSPECIFIED Analysis_State = 0
	// Queued, not yet started.
	Analysis_PENDING Analysis_State = 1
	// MulVAL subprocess is running.
	Analysis_RUNNING Analysis_State = 2
	// Completed successfully. attack_graph is populated.
	Analysis_SUCCEEDED Analysis_State = 3
	// MulVAL returned an error. error field is populated.
	Analysis_FAILED Analysis_State = 4
	// Cancelled by the client.
	Analysis_CANCELLED Analysis_State = 5
)

// Enum value maps for Analysis_State.
var (
	Analysis_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "PENDING",
		2: "RUNNING",
		3: "SUCCEEDED",
		4: "FAILED",
		5: "CANCELLED",
	}
	Analysis_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"PENDING":           1,
		"RUNNING":           2,
		"SUCCEEDED":         3,
		"FAILED":            4,
		"CANCELLED":         5,
	}
)

func (x Analysis_State) Enum() *Analysis_State {
	p := new(Analysis_State)
	*p = x
	return p
}

func (x Analysis_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Analysis_State) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_api_v1_analysis_analysis_proto_enumTypes[0].Descriptor()
}

func (Analysis_State) Type() protoreflect.EnumType {
	return &file_proto_api_v1_analysis_analysis_proto_enumTypes[0]
}

func (x Analysis_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Analysis_State.Descriptor instead.
func (Analysis_State) EnumDescriptor() ([]byte, []int) {
	return file_proto_api_v1_analysis_analysis_proto_rawDescGZIP(), []int{0, 0}
}

type Vertex_VertexType int32

const (
	Vertex_VERTEX_TYPE_UNSPECIFIED Vertex_VertexType = 0
	// A derived logical consequence (AND node).
	Vertex_AND Vertex_VertexType = 1
	// A primitive EDB fact (leaf node).
	Vertex_LEAF Vertex_VertexType = 2
	// An OR node (multiple paths lead here).
	Vertex_OR Vertex_VertexType = 3
)

// Enum value maps for Vertex_VertexType.
var (
	Vertex_VertexType_name = map[int32]string{
		0: "VERTEX_TYPE_UNSPECIFIED",
		1: "AND",
		2: "LEAF",
		3: "OR",
	}
	Vertex_VertexType_value = map[string]int32{
		"VERTEX_TYPE_UNSPECIFIED": 0,
		"AND":                     1,
		"LEAF":                    2,
		"OR":                      3,
	}
)

func (x Vertex_VertexType) Enum() *Vertex_VertexType {
	p := new(Vertex_VertexType)
	*p = x
	return p
}

func (x Vertex_VertexType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Vertex_VertexType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_api_v1_analysis_analysis_proto_enumTypes[1].Descriptor()
}

func (Vertex_VertexType) Type() protoreflect.EnumType {
	return &file_proto_api_v1_analysis_analysis_proto_enumTypes[1]
}

func (x Vertex_VertexType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Vertex_VertexType.Descriptor instead.
func (Vertex_VertexType) EnumDescriptor() ([]byte, []int) {
	return file_proto_api_v1_analysis_analysis_proto_rawDescGZIP(), []int{2, 0}
}

// Analysis represents a single MulVAL attack graph generation run.
// Resource name: analyses/{analysis_id}
type Analysis struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource name. Server-assigned if not provided on creation.
	// Format: analyses/{analysis_id}
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Client-provided idempotency key. If a request with the same
	// analysis_id is received while a run is in progress or completed,
	// the existing operation is returned rather than starting a new run.
	// Optional — server assigns a UUID if omitted.
	AnalysisId string `protobuf:"bytes,2,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	// EDB ground facts in MulVAL Prolog syntax, one clause per entry.
	// Example: "hacl(internet, webServer, tcp, 80)."
	// Required.
	EdbFacts []string `protobuf:"bytes,3,rep,name=edb_facts,json=edbFacts,proto3" json:"edb_facts,omitempty"`
	// Additional IDB interaction rules in MulVAL Prolog syntax.
	// These are appended to the default MulVAL interaction rules via
	// graph_gen.sh -a. Optional — only the default rules apply if empty.
	IdbRules []string `protobuf:"bytes,4,rep,name=idb_rules,json=idbRules,proto3" json:"idb_rules,omitempty"`
	// The state of the analysis.
	State Analysis_State `protobuf:"varint,5,opt,name=state,proto3,enum=proto.api.v1.analysis.Analysis_State" json:"state,omitempty"`
	// When the analysis was created.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// When the analysis completed (succeeded or failed).
	EndTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// The attack graph result. Populated only when state = SUCCEEDED.
	AttackGraph *AttackGraph `protobuf:"bytes,8,opt,name=attack_graph,json=attackGraph,proto3" json:"attack_graph,omitempty"`
	// Human-readable error message. Populated only when state = FAILED.
	Error         string `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Analysis) Reset() {
	*x = Analysis{}
	mi := &file_proto_api_v1_analysis_analysis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Analysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Analysis) ProtoMessage() {}

func (x *Analysis) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_analysis_analysis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Analysis.ProtoReflect.Descriptor instead.
func (*Analysis) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_analysis_analysis_proto_rawDescGZIP(), []int{0}
}

func (x *Analysis) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Analysis) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

func (x *Analysis) GetEdbFacts() []string {
	if x != nil {
		return x.EdbFacts
	}
	return nil
}

func (x *Analysis) GetIdbRules() []string {
	if x != nil {
		return x.IdbRules
	}
	return nil
}

func (x *Analysis) GetState() Analysis_State {
	if x != nil {
		return x.State
	}
	return Analysis_STATE_UNSPECIFIED
}

func (x *Analysis) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Analysis) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Analysis) GetAttackGraph() *AttackGraph {
	if x != nil {
		return x.AttackGraph
	}
	return nil
}

func (x *Analysis) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// AttackGraph is the output of a completed Analysis.
type AttackGraph struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw content of VERTICES.CSV as produced by MulVAL.
	VerticesCsv string `protobuf:"bytes,1,opt,name=vertices_csv,json=verticesCsv,proto3" json:"vertices_csv,omitempty"`
	// Raw content of ARCS.CSV as produced by MulVAL.
	ArcsCsv string `protobuf:"bytes,2,opt,name=arcs_csv,json=arcsCsv,proto3" json:"arcs_csv,omitempty"`
	// Raw content of AttackGraph.txt (MulVAL's text summary).
	Summary string `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	// Parsed vertices for programmatic consumption.
	Vertices []*Vertex `protobuf:"bytes,4,rep,name=vertices,proto3" json:"vertices,omitempty"`
	// Parsed arcs for programmatic consumption.
	Arcs          []*Arc `protobuf:"bytes,5,rep,name=arcs,proto3" json:"arcs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttackGraph) Reset() {
	*x = AttackGraph{}
	mi := &file_proto_api_v1_analysis_analysis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackGraph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackGraph) ProtoMessage() {}

func (x *AttackGraph) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_analysis_analysis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackGraph.ProtoReflect.Descriptor instead.
func (*AttackGraph) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_analysis_analysis_proto_rawDescGZIP(), []int{1}
}

func (x *AttackGraph) GetVerticesCsv() string {
	if x != nil {
		return x.VerticesCsv
	}
	return ""
}

func (x *AttackGraph) GetArcsCsv() string {
	if x != nil {
		return x.ArcsCsv
	}
	return ""
}

func (x *AttackGraph) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *AttackGraph) GetVertices() []*Vertex {
	if x != nil {
		return x.Vertices
	}
	return nil
}

func (x *AttackGraph) GetArcs() []*Arc {
	if x != nil {
		return x.Arcs
	}
	return nil
}

// Vertex represents one node in the attack graph.
type Vertex struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Numeric vertex ID as assigned by MulVAL.
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Prolog fact label (e.g. "execCode(webServer,apache)").
	Fact string `protobuf:"bytes,2,opt,name=fact,proto3" json:"fact,omitempty"`
	// Vertex type as classified by MulVAL.
	VertexType Vertex_VertexType `protobuf:"varint,3,opt,name=vertex_type,json=vertexType,proto3,enum=proto.api.v1.analysis.Vertex_VertexType" json:"vertex_type,omitempty"`
	// Whether this vertex is the declared attackGoal.
	IsGoal        bool `protobuf:"varint,4,opt,name=is_goal,json=isGoal,proto3" json:"is_goal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vertex) Reset() {
	*x = Vertex{}
	mi := &file_proto_api_v1_analysis_analysis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vertex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vertex) ProtoMessage() {}

func (x *Vertex) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_analysis_analysis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vertex.ProtoReflect.Descriptor instead.
func (*Vertex) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_analysis_analysis_proto_rawDescGZIP(), []int{2}
}

func (x *Vertex) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Vertex) GetFact() string {
	if x != nil {
		return x.Fact
	}
	return ""
}

func (x *Vertex) GetVertexType() Vertex_VertexType {
	if x != nil {
		return x.VertexType
	}
	return Vertex_VERTEX_TYPE_UNSPECIFIED
}

func (x *Vertex) GetIsGoal() bool {
	if x != nil {
		return x.IsGoal
	}
	return false
}

// Arc represents a directed edge in the attack graph.
type Arc struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source vertex ID.
	Src int32 `protobuf:"varint,1,opt,name=src,proto3" json:"src,omitempty"`
	// Destination vertex ID.
	Dst           int32 `protobuf:"varint,2,opt,name=dst,proto3" json:"dst,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Arc) Reset() {
	*x = Arc{}
	mi := &file_proto_api_v1_analysis_analysis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Arc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Arc) ProtoMessage() {}

func (x *Arc) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_analysis_analysis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Arc.ProtoReflect.Descriptor instead.
func (*Arc) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_analysis_analysis_proto_rawDescGZIP(), []int{3}
}

func (x *Arc) GetSrc() int32 {
	if x != nil {
		return x.Src
	}
	return 0
}

func (x *Arc) GetDst() int32 {
	if x != nil {
		return x.Dst
	}
	return 0
}

// AnalysisOperationMetadata is embedded in Operation.metadata during a run.
// AIP-151: metadata must describe the current status of the LRO.
type AnalysisOperationMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource name of the analysis being executed.
	Analysis string `protobuf:"bytes,1,opt,name=analysis,proto3" json:"analysis,omitempty"`
	// Current state.
	State Analysis_State `protobuf:"varint,2,opt,name=state,proto3,enum=proto.api.v1.analysis.Analysis_State" json:"state,omitempty"`
	// When the operation was created.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// When the operation last changed state.
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisOperationMetadata) Reset() {
	*x = AnalysisOperationMetadata{}
	mi := &file_proto_api_v1_analysis_analysis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisOperationMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisOperationMetadata) ProtoMessage() {}

func (x *AnalysisOperationMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_analysis_analysis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisOperationMetadata.ProtoReflect.Descriptor instead.
func (*AnalysisOperationMetadata) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_analysis_analysis_proto_rawDescGZIP(), []int{4}
}

func (x *AnalysisOperationMetadata) GetAnalysis() string {
	if x != nil {
		return x.Analysis
	}
	return ""
}

func (x *AnalysisOperationMetadata) GetState() Analysis_State {
	if x != nil {
		return x.State
	}
	return Analysis_STATE_UNSPECIFIED
}

func (x *AnalysisOperationMetadata) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *AnalysisOperationMetadata) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type CreateAnalysisRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource name. Server-assigned if not provided on creation.
	// Format: analyses/{analysis_id}
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Client-provided idempotency key. If a request with the same
	// analysis_id is received while a run is in progress or completed,
	// the existing operation is returned rather than starting a new run.
	// Optional — server assigns a UUID if omitted.
	AnalysisId string `protobuf:"bytes,2,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	// EDB ground facts in MulVAL Prolog syntax, one clause per entry.
	// Example: "hacl(internet, webServer, tcp, 80)."
	// Required.
	EdbFacts []string `protobuf:"bytes,3,rep,name=edb_facts,json=edbFacts,proto3" json:"edb_facts,omitempty"`
	// Additional IDB interaction rules in MulVAL Prolog syntax.
	// These are appended to the default MulVAL interaction rules via
	// graph_gen.sh -a. Optional — only the default rules apply if empty.
	IdbRules      []string `protobuf:"bytes,4,rep,name=idb_rules,json=idbRules,proto3" json:"idb_rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAnalysisRequest) Reset() {
	*x = CreateAnalysisRequest{}
	mi := &file_proto_api_v1_analysis_analysis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnalysisRequest) ProtoMessage() {}

func (x *CreateAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_analysis_analysis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnalysisRequest.ProtoReflect.Descriptor instead.
func (*CreateAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_analysis_analysis_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAnalysisRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAnalysisRequest) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

func (x *CreateAnalysisRequest) GetEdbFacts() []string {
	if x != nil {
		return x.EdbFacts
	}
	return nil
}

func (x *CreateAnalysisRequest) GetIdbRules() []string {
	if x != nil {
		return x.IdbRules
	}
	return nil
}

type GetAnalysisRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource name of the analysis to retrieve.
	// Format: analyses/{analysis_id}
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnalysisRequest) Reset() {
	*x = GetAnalysisRequest{}
	mi := &file_proto_api_v1_analysis_analysis_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalysisRequest) ProtoMessage() {}

func (x *GetAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_analysis_analysis_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalysisRequest.ProtoReflect.Descriptor instead.
func (*GetAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_analysis_analysis_proto_rawDescGZIP(), []int{6}
}

func (x *GetAnalysisRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListAnalysesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of analyses to return.
	// Defaults to 50 if unset or zero. Maximum is 1000.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Opaque token returned by a previous ListAnalyses call.
	// Leave empty to start from the beginning.
	PageToken     string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAnalysesRequest) Reset() {
	*x = ListAnalysesRequest{}
	mi := &file_proto_api_v1_analysis_analysis_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAnalysesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnalysesRequest) ProtoMessage() {}

func (x *ListAnalysesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_analysis_analysis_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnalysesRequest.ProtoReflect.Descriptor instead.
func (*ListAnalysesRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_analysis_analysis_proto_rawDescGZIP(), []int{7}
}

func (x *ListAnalysesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAnalysesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListAnalysesResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Analyses []*Analysis            `protobuf:"bytes,1,rep,name=analyses,proto3" json:"analyses,omitempty"`
	// Token to retrieve the next page.
	// Empty when there are no more results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAnalysesResponse) Reset() {
	*x = ListAnalysesResponse{}
	mi := &file_proto_api_v1_analysis_analysis_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAnalysesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnalysesResponse) ProtoMessage() {}

func (x *ListAnalysesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_analysis_analysis_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnalysesResponse.ProtoReflect.Descriptor instead.
func (*ListAnalysesResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_analysis_analysis_proto_rawDescGZIP(), []int{8}
}

func (x *ListAnalysesResponse) GetAnalyses() []*Analysis {
	if x != nil {
		return x.Analyses
	}
	return nil
}

func (x *ListAnalysesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_proto_api_v1_analysis_analysis_proto protoreflect.FileDescriptor

const file_proto_api_v1_analysis_analysis_proto_rawDesc = "" +
	"\n" +
	"$proto/api/v1/analysis/analysis.proto\x12\x15proto.api.v1.analysis\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a#google/longrunning/operations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd7\x04\n" +
	"\bAnalysis\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vanalysis_id\x18\x02 \x01(\tR\n" +
	"analysisId\x12 \n" +
	"\tedb_facts\x18\x03 \x03(\tB\x03\xe0A\x02R\bedbFacts\x12\x1b\n" +
	"\tidb_rules\x18\x04 \x03(\tR\bidbRules\x12@\n" +
	"\x05state\x18\x05 \x01(\x0e2%.proto.api.v1.analysis.Analysis.StateB\x03\xe0A\x03R\x05state\x12@\n" +
	"\vcreate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x12:\n" +
	"\bend_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\aendTime\x12J\n" +
	"\fattack_graph\x18\b \x01(\v2\".proto.api.v1.analysis.AttackGraphB\x03\xe0A\x03R\vattackGraph\x12\x19\n" +
	"\x05error\x18\t \x01(\tB\x03\xe0A\x03R\x05error\"b\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\v\n" +
	"\aRUNNING\x10\x02\x12\r\n" +
	"\tSUCCEEDED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04\x12\r\n" +
	"\tCANCELLED\x10\x05:L\xeaAI\n" +
	"\x1emulval.cvewatcher.dev/Analysis\x12\x13analyses/{analysis}*\banalyses2\banalysis\"\xd0\x01\n" +
	"\vAttackGraph\x12!\n" +
	"\fvertices_csv\x18\x01 \x01(\tR\vverticesCsv\x12\x19\n" +
	"\barcs_csv\x18\x02 \x01(\tR\aarcsCsv\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x129\n" +
	"\bvertices\x18\x04 \x03(\v2\x1d.proto.api.v1.analysis.VertexR\bvertices\x12.\n" +
	"\x04arcs\x18\x05 \x03(\v2\x1a.proto.api.v1.analysis.ArcR\x04arcs\"\xd6\x01\n" +
	"\x06Vertex\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04fact\x18\x02 \x01(\tR\x04fact\x12I\n" +
	"\vvertex_type\x18\x03 \x01(\x0e2(.proto.api.v1.analysis.Vertex.VertexTypeR\n" +
	"vertexType\x12\x17\n" +
	"\ais_goal\x18\x04 \x01(\bR\x06isGoal\"D\n" +
	"\n" +
	"VertexType\x12\x1b\n" +
	"\x17VERTEX_TYPE_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03AND\x10\x01\x12\b\n" +
	"\x04LEAF\x10\x02\x12\x06\n" +
	"\x02OR\x10\x03\")\n" +
	"\x03Arc\x12\x10\n" +
	"\x03src\x18\x01 \x01(\x05R\x03src\x12\x10\n" +
	"\x03dst\x18\x02 \x01(\x05R\x03dst\"\x93\x02\n" +
	"\x19AnalysisOperationMetadata\x12?\n" +
	"\banalysis\x18\x01 \x01(\tB#\xfaA \n" +
	"\x1emulval.cvewatcher.dev/AnalysisR\banalysis\x12;\n" +
	"\x05state\x18\x02 \x01(\x0e2%.proto.api.v1.analysis.Analysis.StateR\x05state\x12;\n" +
	"\vcreate_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"\x8b\x01\n" +
	"\x15CreateAnalysisRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vanalysis_id\x18\x02 \x01(\tR\n" +
	"analysisId\x12 \n" +
	"\tedb_facts\x18\x03 \x03(\tB\x03\xe0A\x02R\bedbFacts\x12\x1b\n" +
	"\tidb_rules\x18\x04 \x03(\tR\bidbRules\"P\n" +
	"\x12GetAnalysisRequest\x12:\n" +
	"\x04name\x18\x01 \x01(\tB&\xe0A\x02\xfaA \n" +
	"\x1emulval.cvewatcher.dev/AnalysisR\x04name\"Q\n" +
	"\x13ListAnalysesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"{\n" +
	"\x14ListAnalysesResponse\x12;\n" +
	"\banalyses\x18\x01 \x03(\v2\x1f.proto.api.v1.analysis.AnalysisR\banalyses\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\xb8\x03\n" +
	"\x0fAnalysisService\x12\xa2\x01\n" +
	"\x0eCreateAnalysis\x12,.proto.api.v1.analysis.CreateAnalysisRequest\x1a\x1d.google.longrunning.Operation\"C\xcaA%\n" +
	"\bAnalysis\x12\x19AnalysisOperationMetadata\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/analyses\x12|\n" +
	"\vGetAnalysis\x12).proto.api.v1.analysis.GetAnalysisRequest\x1a\x1f.proto.api.v1.analysis.Analysis\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/{name=analyses/*}\x12\x81\x01\n" +
	"\fListAnalyses\x12*.proto.api.v1.analysis.ListAnalysesRequest\x1a+.proto.api.v1.analysis.ListAnalysesResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/analysesB=Z;github.com/cvewatcher/mulval/proto/api/v1/analysis;analysisb\x06proto3"

var (
	file_proto_api_v1_analysis_analysis_proto_rawDescOnce sync.Once
	file_proto_api_v1_analysis_analysis_proto_rawDescData []byte
)

func file_proto_api_v1_analysis_analysis_proto_rawDescGZIP() []byte {
	file_proto_api_v1_analysis_analysis_proto_rawDescOnce.Do(func() {
		file_proto_api_v1_analysis_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_api_v1_analysis_analysis_proto_rawDesc), len(file_proto_api_v1_analysis_analysis_proto_rawDesc)))
	})
	return file_proto_api_v1_analysis_analysis_proto_rawDescData
}

var file_proto_api_v1_analysis_analysis_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_api_v1_analysis_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_api_v1_analysis_analysis_proto_goTypes = []any{
	(Analysis_State)(0),               // 0: proto.api.v1.analysis.Analysis.State
	(Vertex_VertexType)(0),            // 1: proto.api.v1.analysis.Vertex.VertexType
	(*Analysis)(nil),                  // 2: proto.api.v1.analysis.Analysis
	(*AttackGraph)(nil),               // 3: proto.api.v1.analysis.AttackGraph
	(*Vertex)(nil),                    // 4: proto.api.v1.analysis.Vertex
	(*Arc)(nil),                       // 5: proto.api.v1.analysis.Arc
	(*AnalysisOperationMetadata)(nil), // 6: proto.api.v1.analysis.AnalysisOperationMetadata
	(*CreateAnalysisRequest)(nil),     // 7: proto.api.v1.analysis.CreateAnalysisRequest
	(*GetAnalysisRequest)(nil),        // 8: proto.api.v1.analysis.GetAnalysisRequest
	(*ListAnalysesRequest)(nil),       // 9: proto.api.v1.analysis.ListAnalysesRequest
	(*ListAnalysesResponse)(nil),      // 10: proto.api.v1.analysis.ListAnalysesResponse
	(*timestamppb.Timestamp)(nil),     // 11: google.protobuf.Timestamp
	(*longrunningpb.Operation)(nil),   // 12: google.longrunning.Operation
}
var file_proto_api_v1_analysis_analysis_proto_depIdxs = []int32{
	0,  // 0: proto.api.v1.analysis.Analysis.state:type_name -> proto.api.v1.analysis.Analysis.State
	11, // 1: proto.api.v1.analysis.Analysis.create_time:type_name -> google.protobuf.Timestamp
	11, // 2: proto.api.v1.analysis.Analysis.end_time:type_name -> google.protobuf.Timestamp
	3,  // 3: proto.api.v1.analysis.Analysis.attack_graph:type_name -> proto.api.v1.analysis.AttackGraph
	4,  // 4: proto.api.v1.analysis.AttackGraph.vertices:type_name -> proto.api.v1.analysis.Vertex
	5,  // 5: proto.api.v1.analysis.AttackGraph.arcs:type_name -> proto.api.v1.analysis.Arc
	1,  // 6: proto.api.v1.analysis.Vertex.vertex_type:type_name -> proto.api.v1.analysis.Vertex.VertexType
	0,  // 7: proto.api.v1.analysis.AnalysisOperationMetadata.state:type_name -> proto.api.v1.analysis.Analysis.State
	11, // 8: proto.api.v1.analysis.AnalysisOperationMetadata.create_time:type_name -> google.protobuf.Timestamp
	11, // 9: proto.api.v1.analysis.AnalysisOperationMetadata.update_time:type_name -> google.protobuf.Timestamp
	2,  // 10: proto.api.v1.analysis.ListAnalysesResponse.analyses:type_name -> proto.api.v1.analysis.Analysis
	7,  // 11: proto.api.v1.analysis.AnalysisService.CreateAnalysis:input_type -> proto.api.v1.analysis.CreateAnalysisRequest
	8,  // 12: proto.api.v1.analysis.AnalysisService.GetAnalysis:input_type -> proto.api.v1.analysis.GetAnalysisRequest
	9,  // 13: proto.api.v1.analysis.AnalysisService.ListAnalyses:input_type -> proto.api.v1.analysis.ListAnalysesRequest
	12, // 14: proto.api.v1.analysis.AnalysisService.CreateAnalysis:output_type -> google.longrunning.Operation
	2,  // 15: proto.api.v1.analysis.AnalysisService.GetAnalysis:output_type -> proto.api.v1.analysis.Analysis
	10, // 16: proto.api.v1.analysis.AnalysisService.ListAnalyses:output_type -> proto.api.v1.analysis.ListAnalysesResponse
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_api_v1_analysis_analysis_proto_init() }
func file_proto_api_v1_analysis_analysis_proto_init() {
	if File_proto_api_v1_analysis_analysis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_api_v1_analysis_analysis_proto_rawDesc), len(file_proto_api_v1_analysis_analysis_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_api_v1_analysis_analysis_proto_goTypes,
		DependencyIndexes: file_proto_api_v1_analysis_analysis_proto_depIdxs,
		EnumInfos:         file_proto_api_v1_analysis_analysis_proto_enumTypes,
		MessageInfos:      file_proto_api_v1_analysis_analysis_proto_msgTypes,
	}.Build()
	File_proto_api_v1_analysis_analysis_proto = out.File
	file_proto_api_v1_analysis_analysis_proto_goTypes = nil
	file_proto_api_v1_analysis_analysis_proto_depIdxs = nil
}
